export class ProductSelectorStore {

    public getConditionerOuterHtml(): string {
        return "<select-product-multiple class=\"block w-full flex flex-col shadow rounded-[20px]\"><div class=\"flex flex-col h-full min-h-[110px]\"><img alt=\"Product image\" class=\"aspect-1 object-cover rounded-[20px]\" src=\"https://storage.googleapis.com/beeoclock-develop.appspot.com/media/662a4637a4b376d20c065b1d/product/68360872ad18ae278466afbc/image/6836089d67fbf228d7a9193a/original.jpeg?updatedAt=2025-05-27T18:46:53.424Z\"><div class=\"flex flex-1 flex-col p-3 justify-between\"><div class=\"flex flex-wrap gap-2 mb-2\"><div class=\"rounded-full bg-neutral-200 px-3 py-1 text-xs font-medium text-neutral-700\"> antea </div><!--container--></div><h3 class=\"flex-1 text-base font-semibold text-mainTextColor leading-none\"> Odżywka </h3><!--container--><div class=\"flex flex-col w-full justify-between items-center mt-4\"><div class=\"self-start\"><div class=\"text-start text-sm font-medium text-black\"> 200,00&nbsp;zł </div></div><div class=\"flex items-center gap-4 self-end\"><!--container--><button aria-label=\"Increment\" class=\"flex max-h-[40px] min-h-[40px] min-w-[40px] max-w-[40px] items-center justify-center rounded-full border-2 border-[--primary-color]\"><i class=\"bi bi-plus-lg text-3xl text-[--primary-color]\"></i></button></div></div><!--container--></div></div><!--container--><!--container--><!--container--></select-product-multiple>"
    }

    public getHairMaskOuterHtml(): string {
        return "<select-product-multiple class=\"block w-full flex flex-col shadow rounded-[20px]\"><div class=\"flex flex-col h-full min-h-[110px]\"><img alt=\"Product image\" class=\"aspect-1 object-cover rounded-[20px]\" src=\"https://storage.googleapis.com/beeoclock-develop.appspot.com/media/662a4637a4b376d20c065b1d/product/685e97a9d183247a48e49bfa/image/685e98bf6b9f94f626fb8b5b/original.png?updatedAt=2025-06-27T13:12:31.187Z\"><div class=\"flex flex-1 flex-col p-3 justify-between\"><div class=\"flex flex-wrap gap-2 mb-2\"><div class=\"rounded-full bg-neutral-200 px-3 py-1 text-xs font-medium text-neutral-700\"> delicate </div><!--container--></div><h3 class=\"flex-1 text-base font-semibold text-mainTextColor leading-none\"> Maska do włosów </h3><div class=\"font-light text-sm text-neutral-500 leading-none mt-2\"> odżywcza Maska do włosów </div><!--container--><div class=\"flex flex-col w-full justify-between items-center mt-4\"><div class=\"self-start\"><div class=\"text-start text-sm font-medium text-black\"> 50,00&nbsp;zł </div></div><div class=\"flex items-center gap-4 self-end\"><!--container--><button aria-label=\"Increment\" class=\"flex max-h-[40px] min-h-[40px] min-w-[40px] max-w-[40px] items-center justify-center rounded-full border-2 border-[--primary-color]\"><i class=\"bi bi-plus-lg text-3xl text-[--primary-color]\"></i></button></div></div><!--container--></div></div><!--container--><!--container--><!--container--></select-product-multiple>"
    }
}