export enum TabNameEnum {
    CALENDAR = 'Kalendarz',
    CLIENTS = 'Klienci',
    ORDER = 'Zamówienia',
    SERVICE = 'Usługi',
    ABSENCE = 'Nieobecność',
    TARIFFS = 'Taryfy',
    BUSINESS_SETTINGS = 'Ustawienia firmy',
    MEMBERS = 'Członkowie',
    PAYMENTS = 'Płatności',
    VISITS = 'Wizyty',
    STATISTICS = 'Statystyki',
    BUSINESS_PROFILE = 'Profil biznesowy',
    BALANCE = 'Saldo',
}