name: Client app Health Check Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 16 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.KEY }}
      PROD_API_KEY: ${{ secrets.PROD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install

      - name: Set locale to Polish
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
        env:
          LANG: pl_PL.UTF-8
          LC_ALL: pl_PL.UTF-8

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Warsaw

      - name: Debug locale and timezone
        run: |
          echo "Current locale:"
          locale
          echo "Current timezone:"
          timedatectl

      - name: Run tests
        env:
          LANG: pl
          LC_ALL: pl_PL.UTF-8
          TZ: Europe/Warsaw
        run: npm run client-app-health-check
