name: Panel App API test Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 16 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.KEY }}
      X_GITHUB_ACTION: ${{ secrets.X_GITHUB_ACTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run panel Api test
        run: npm run panel-app-api-test